version: '3.8'

services:
  # Backend API Service
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api_service
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=3000
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@database:${DB_PORT}/${DB_NAME}
    volumes: # Maps host ./api to container /usr/src/app and overrides node_modules with a Docker volume
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
      - ./logs:/usr/src/app/logs
    depends_on:
      - database
    networks:
      - app-network

  # Frontend React App
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: react_app
    ports:
      - "5173:5173"
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
      - ./logs:/usr/src/app/logs  # Mount logs to container
    environment:
      - VITE_API_URL=http://localhost:3000
    networks:
      - app-network
    restart: unless-stopped

  # Reverse Proxy (Nginx)
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - app
    networks:
      - app-network

  # Database Service 
  database:
    image: postgres:15
    container_name: ics_postgres_db_dev
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_dev_data:
    driver: local

networks:
  app-network:
    driver: bridge
